version: '2.7'
services:
  terraform-base:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    volumes:
      - $PWD/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    working_dir: /work
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-east-2
      - TF_VAR_domain_name=${DOMAIN_NAME}
      - TF_VAR_customer_name=${CUSTOMER_NAME}
      - TF_VAR_product_name=${PRODUCT_NAME}
  terraform-init-base:
    extends: terraform-base
    entrypoint: bash
    environment:
      DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION: us-east-2
    command:
      - -c
      - "{ test -z ${REINIT} && test -f /work/.terraform/initialized; } && exit 0; \
         /scripts/create_backend.sh && \
         git config --global --add safe.directory '*' && \
         terraform init -backend-config=/tmp/conf.tfbackend && \
         touch /work/.terraform/initialized"
  terraform:
    extends: terraform-base
    volumes:
      - $PWD/infrastructure/core:/work
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-east-2
      - TF_VAR_domain_name=${DOMAIN_NAME}
      - TF_VAR_customer_name=${CUSTOMER_NAME}
      - TF_VAR_product_name=${PRODUCT_NAME}
  terraform-init:
    extends: terraform-init-base
    volumes:
      - $PWD/infrastructure/core:/work
  terraform-plan:
    extends: terraform
    command:
      - plan
      - -input=false
  terraform-apply:
    extends: terraform
    command:
      - apply
      - -input=false
      - -auto-approve
      - -compact-warnings
  terraform-keycloak:
    extends: terraform-base
    volumes:
      - $PWD/infrastructure/keycloak:/work
    environment:
      - TF_LOG
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_CLIENT_ID=admin-cli
      - KEYCLOAK_URL=https://keycloak.${DNS_TMC_DOMAIN}
      - TERRAFORM_STATE_S3_BUCKET_NAME="${TERRAFORM_STATE_S3_KEYCLOAK_BUCKET_NAME}"
      - TERRAFORM_STATE_S3_BUCKET_KEY="${TERRAFORM_STATE_S3_KEYCLOAK_BUCKET_KEY}"
      - TF_VAR_dns_tmc_domain=${DNS_TMC_DOMAIN}
      - TF_VAR_keycloak_test_user=$KEYCLOAK_TEST_USER
      - TF_VAR_keycloak_test_password=$KEYCLOAK_TEST_PASSWORD
  terraform-init-keycloak:
    extends: terraform-init-base
    volumes:
      - $PWD/infrastructure/keycloak:/work
    environment:
      - TERRAFORM_STATE_S3_BUCKET_NAME=${TERRAFORM_STATE_S3_KEYCLOAK_BUCKET_NAME}
      - TERRAFORM_STATE_S3_BUCKET_KEY=${TERRAFORM_STATE_S3_KEYCLOAK_BUCKET_KEY}
  terraform-plan-keycloak:
    extends: terraform-keycloak
    command:
      - plan
      - -input=false
  terraform-apply-keycloak:
    extends: terraform-keycloak
    command:
      - apply
      - -input=false
      - -auto-approve
      - -compact-warnings
  terraform-output-keycloak:
    extends: terraform-keycloak
    command:
      - output
      - -json
  terraform-example-clusters:
    extends: terraform-base
    volumes:
      - $PWD/infrastructure/example-clusters:/work
    environment:
      - TF_LOG
      - TERRAFORM_STATE_S3_BUCKET_NAME="${TERRAFORM_STATE_S3_EXAMPLE_CLUSTERS_BUCKET_NAME}"
      - TERRAFORM_STATE_S3_BUCKET_KEY="${TERRAFORM_STATE_S3_EXAMPLE_CLUSTERS_BUCKET_KEY}"
      - OIDC_ISSUER=pinniped-supervisor.${DNS_TMC_DOMAIN}
      - TMC_ENDPOINT=compute.${DNS_TMC_DOMAIN}
      - TMC_SM_USERNAME
      - TMC_SM_PASSWORD
  terraform-init-example-clusters:
    extends: terraform-init-base
    volumes:
      - $PWD/infrastructure/example-clusters:/work
    environment:
      - TERRAFORM_STATE_S3_BUCKET_NAME=${TERRAFORM_STATE_S3_EXAMPLE_CLUSTERS_BUCKET_NAME}
      - TERRAFORM_STATE_S3_BUCKET_KEY=${TERRAFORM_STATE_S3_EXAMPLE_CLUSTERS_BUCKET_KEY}
  terraform-plan-example-clusters:
    extends: terraform-example-clusters
    command:
      - plan
      - -input=false
  terraform-apply-example-clusters:
    extends: terraform-example-clusters
    command:
      - apply
      - -input=false
      - -auto-approve
      - -compact-warnings
  terraform-output-example-clusters:
    extends: terraform-example-clusters
    command:
      - output
      - -json
