version: '2.7'
services:
  terraform:
    image: carlosnunez/terraform:1.4.1-arm64
    working_dir: /work
    volumes:
      - $PWD:/work
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-east-2
      - TF_VAR_domain_name=${DOMAIN_NAME}
      - TF_VAR_customer_name=${CUSTOMER_NAME}
      - TF_VAR_product_name=${PRODUCT_NAME}
  terraform-init:
    extends: terraform
    entrypoint: bash
    environment:
      DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION: us-east-2
    command:
      - -c
      - "{ test -z ${REINIT} && test -f /work/.terraform/initialized; } && exit 0; \
         ./scripts/create_backend.sh && \
         git config --global --add safe.directory '*' && \
         terraform init -backend-config=/tmp/conf.tfbackend && \
         touch /work/.terraform/initialized"
  terraform-plan:
    extends: terraform
    command:
      - plan
      - -input=false
  terraform-apply:
    extends: terraform
    command:
      - apply
      - -input=false
      - -auto-approve
      - -compact-warnings
  terraform-output:
    extends: terraform
    command:
      - output
      - -json
