apiVersion: v1
kind: Secret
metadata:
  name: kali-linux-desktop-secret
  namespace: example-student-example-course-2
  labels:
    course: "h31a-cyber-threat-course"
type: Opaque
data:
  vnc_password: c3VwZXJzZWNyZXQK

