#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: local-ca
  namespace: cert-manager
data:
  tls.crt: #@ data.values.certificate
  tls.key: #@ data.values.key
type: kubernetes.io/tls

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-issuer
spec:
  ca:
    secretName: local-ca

