#@ load("@ytt:data", "data")
clusterIssuer: #@ data.values.cluster_issuer
dnsZone: #@ data.values.domain
harborProject: #@ data.values.harbor_repo
minio:
 password: #@ data.values.minio_password
 username: admin
oidc:
 clientID: #@ data.values.keycloak_client_id
 clientSecret: #@ data.values.keycloak_client_secret
 issuerType: pinniped
 issuerURL: #@ data.values.keycloak_client_url
telemetry:
 ceipAgreement: false
 ceipOptIn: false
contourEnvoy:
 serviceType: LoadBalancer
postgres:
 userPassword: #@ "{}".format(data.values.tmc_postgres_password)
trustedCAs:
 letsencrypt.pem: #@ data.values.lets_encrypt_chain
