#!/usr/bin/env bash
set -eo pipefail
DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION="${DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION?DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION should be in Docker Compose}"
TERRAFORM_STATE_S3_BUCKET_NAME="${TERRAFORM_STATE_S3_BUCKET_NAME?Please define TERRAFORM_STATE_S3_BUCKET_NAME in your .env}"
TERRAFORM_STATE_S3_BUCKET_KEY="${TERRAFORM_STATE_S3_BUCKET_KEY?Please define TERRAFORM_STATE_S3_BUCKET_KEY in your .env}"
TERRAFORM_BACKEND_CONF_LOCATION=/tmp/conf.tfbackend

aws_region() {
  test -n "$AWS_REGION" && { echo "$AWS_REGION" && return 0; }
  test -n "$TERRAFORM_STATE_S3_BUCKET_REGION" && { echo "$TERRAFORM_STATE_S3_BUCKET_REGION" && return 0; }
  echo "$DEFAULT_TERRAFORM_STATE_S3_BUCKET_REGION"
}

>&2 echo "========> Writing backend to $TERRAFORM_BACKEND_CONF_LOCATION"
cat >"$TERRAFORM_BACKEND_CONF_LOCATION" <<-EOF
bucket = "$TERRAFORM_STATE_S3_BUCKET_NAME"
key = "$TERRAFORM_STATE_S3_BUCKET_KEY"
region = "$(aws_region)"
EOF
